#!/bin/bash

sudo yum install java-1.8.0-openjdk-devel -y

sudo yum install wget -y
sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
sudo sed -i 's/gpgcheck=1/gpgcheck=0/g' /etc/yum.repos.d/jenkins.repo

sudo yum install jenkins -y
sudo systemctl start jenkins 
sudo systemctl status jenkins
sudo systemctl enable jenkins

sudo yum install firewalld -y
sudo systemctl start firewalld
sudo systemctl status firewalld
sudo systemctl enable firewalld
sudo firewall-cmd --permanent --zone=public --add-port=8080/tcp 
sudo firewall-cmd --reload
sudo yum install net-tools -y
